---
stage: dev
region: us-east-1
accountId: accountId
iamrole: arn:aws:iam::accountId:role/Lambda
privateKey: 37LvDSm5XvjYOh9Y
authFunction: arn:aws:lambda:region:accountId:function:custom-authorizer
tables:
  users:
    name: Users
    gsi:
      email: 
        name: UsersEmailGsi
